###############################################################################
#                          Generated on phpdocker.io                          #
###############################################################################
version: "3.1"
services:

    redis:
      image: redis:alpine
      container_name: hospital-redis
      networks:
      - app-network

    mysql:
      image: mysql:8.0
      container_name: hospital-mysql
      working_dir: /application
      volumes:
        - .:/application
      environment:
        - MYSQL_ROOT_PASSWORD=root
        - MYSQL_DATABASE=db_hospital
        - MYSQL_USER=root
        - MYSQL_PASSWORD=root
      ports:
        - "9002:3306"
      networks:
      - app-network

    webserver:
      image: nginx:alpine
      container_name: hospital-webserver
      working_dir: /application
      volumes:
          - .:/application
          - ./phpdocker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      ports:
       - "9001:80"
      networks:
      - app-network

    php-fpm:
      build: phpdocker/php-fpm
      container_name: hospital-php-fpm
      working_dir: /application
      volumes:
        - .:/application
        - ./phpdocker/php-fpm/php-ini-overrides.ini:/etc/php/7.3/fpm/conf.d/99-overrides.ini
      networks:
      - app-network

    #Docker Networks
networks:
  app-network:
    driver: bridge